# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  format:
    desc: Format all files
    cmds:
      - echo -e 'oxfmt\nnixfmt **/*.nix\nruff format --line-length 120 **/*.py\n' | xargs -I{} -P 3 sh -c '{}'
    silent: true
